/* TENANT */
export const PEOPLES_LOADING = 'PEOPLES_LOADING'

export const GET_PEOPLES = 'GET_PEOPLES'
export const GET_PEOPLES_SUCCESS = 'GET_PEOPLES_SUCCESS'
export const GET_PEOPLES_FAIL = 'GET_PEOPLES_FAIL'

export const GET_AGENCIES_BY_COMPANY = 'GET_AGENCIES_BY_COMPANY'
export const GET_AGENCIES_BY_COMPANY_SUCCESS = 'GET_AGENCIES_BY_COMPANY_SUCCESS'
export const GET_AGENCIES_BY_COMPANY_FAIL = 'GET_AGENCIES_BY_COMPANY_FAIL'

export const GET_PERSONS_BY_COMPANY = 'GET_PERSONS_BY_COMPANY'
export const GET_PERSONS_BY_COMPANY_SUCCESS = 'GET_PERSONS_BY_COMPANY_SUCCESS'
export const GET_PERSONS_BY_COMPANY_FAIL = 'GET_PERSONS_BY_COMPANY_FAIL'

export const GET_PERSONS_BY_AGENCY = 'GET_PERSONS_BY_AGENCY'
export const GET_PERSONS_BY_AGENCY_SUCCESS = 'GET_PERSONS_BY_AGENCY_SUCCESS'
export const GET_PERSONS_BY_AGENCY_FAIL = 'GET_PERSONS_BY_AGENCY_FAIL'

export const CREATE_PEOPLES = 'CREATE_PEOPLES'
export const CREATE_PEOPLES_SUCESS = 'CREATE_PEOPLES_SUCESS'
export const UPDATE_PEOPLES = 'UPDATE_PEOPLES'
export const DELETE_PEOPLES = 'DELETE_PEOPLES'

export const GET_PEOPLES_USERS = 'GET_PEOPLES_USERS'
export const GET_PEOPLES_USERS_SUCCESS = 'GET_PEOPLES_USERS_SUCCESS'
export const GET_PEOPLES_USERS_FAIL = 'GET_PEOPLES_USERS_FAIL'

export const CREATE_LEAD = 'CREATE_LEAD'
