// Lead Details
export const GET_LEAD_DETAILS_BY_ID_REQUEST = 'GET_LEAD_DETAILS_BY_ID_REQUEST'
export const GET_LEAD_DETAILS_BY_ID_SUCCESS = 'GET_LEAD_DETAILS_BY_ID_SUCCESS'
export const GET_LEAD_DETAILS_BY_ID_FAILURE = 'GET_LEAD_DETAILS_BY_ID_FAILURE'
export const RESET_LEAD_DETAILS = 'RESET_LEAD_DETAILS'

export const UPDATE_LEAD_STEP_REQUEST = 'UPDATE_LEAD_STEP_REQUEST'
export const UPDATE_LEAD_STEP_SUCCESS = 'UPDATE_LEAD_STEP_SUCCESS'
export const UPDATE_LEAD_STEP_FAILURE = 'UPDATE_LEAD_STEP_FAILURE'

// Lead Tasks
export const GET_LEAD_TASKS_REQUEST = 'GET_LEAD_TASKS_REQUEST'
export const GET_LEAD_TASKS_SUCCESS = 'GET_LEAD_TASKS_SUCCESS'
export const GET_LEAD_TASKS_FAILURE = 'GET_LEAD_TASKS_FAILURE'
export const TOGGLE_TASK = 'LEAD_TOGGLE_TASK'
export const DELETE_TASK_REQUEST = 'DELETE_TASK_REQUEST'

export const CREATE_TASK_REQUEST = 'CREATE_TASK_REQUEST'
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS'
export const CREATE_TASK_FAILURE = 'CREATE_TASK_FAILURE'

// Lead Observations
export const GET_LEAD_OBSERVATIONS_REQUEST = 'GET_LEAD_OBSERVATIONS_REQUEST'
export const GET_LEAD_OBSERVATIONS_SUCCESS = 'GET_LEAD_OBSERVATIONS_SUCCESS'
export const GET_LEAD_OBSERVATIONS_FAILURE = 'GET_LEAD_OBSERVATIONS_FAILURE'

export const CREATE_LEAD_OBSERVATION_REQUEST = 'CREATE_LEAD_OBSERVATION_REQUEST'
export const CREATE_LEAD_OBSERVATION_SUCCESS = 'CREATE_LEAD_OBSERVATION_SUCCESS'
export const CREATE_LEAD_OBSERVATION_FAILURE = 'CREATE_LEAD_OBSERVATION_FAILURE'

// Lead Meetings
export const GET_LEAD_MEETINGS_REQUEST = 'GET_LEAD_MEETINGS_REQUEST'
export const GET_LEAD_MEETINGS_SUCCESS = 'GET_LEAD_MEETINGS_SUCCESS'
export const GET_LEAD_MEETINGS_FAILURE = 'GET_LEAD_MEETINGS_FAILURE'

export const CREATE_MEETING_REQUEST = 'CREATE_MEETING_REQUEST'
export const CREATE_MEETING_SUCCESS = 'CREATE_MEETING_SUCCESS'
export const CREATE_MEETING_FAILURE = 'CREATE_MEETING_FAILURE'
