export const GET_WORKFLOWS_REQUEST = 'GET_WORKFLOWS_REQUEST'
export const GET_WORKFLOWS_SUCCESS = 'GET_WORKFLOWS_SUCCESS'
export const GET_WORKFLOWS_FAILURE = 'GET_WORKFLOWS_FAILURE'

export const CREATE_WORKFLOW_REQUEST = 'CREATE_WORKFLOW_REQUEST'
export const CREATE_WORKFLOW_SUCCESS = 'CREATE_WORKFLOW_SUCCESS'
export const CREATE_WORKFLOW_FAILURE = 'CREATE_WORKFLOW_FAILURE'

export const UPDATE_WORKFLOW_REQUEST = 'UPDATE_WORKFLOW_REQUEST'
export const UPDATE_WORKFLOW_SUCCESS = 'UPDATE_WORKFLOW_SUCCESS'
export const UPDATE_WORKFLOW_FAILURE = 'UPDATE_WORKFLOW_FAILURE'

export const DELETE_WORKFLOW_REQUEST = 'DELETE_WORKFLOW_REQUEST'
export const DELETE_WORKFLOW_SUCCESS = 'DELETE_WORKFLOW_SUCCESS'
export const DELETE_WORKFLOW_FAILURE = 'DELETE_WORKFLOW_FAILURE'
