export const IMPORT_LEADS_REQUEST = 'IMPORT_LEADS_REQUEST'
export const IMPORT_LEADS_SUCCESS = 'IMPORT_LEADS_SUCCESS'
export const IMPORT_LEADS_FAILURE = 'IMPORT_LEADS_FAILURE'
export const CONFIRM_IMPORT_LEADS = 'CONFIRM_IMPORT_LEADS'
